### ISSUE TITLE
DNS Resolution Failure to MongoDb Atlas

### ISSUE THREAD

**Issue by twilcomgistix** [nightroman/Mdbc#69]
When connecting to my Atlas instance with Mdbc Powershell module, I get the following error response:

I've redacted part of the hostname

```powershell
PSMessageDetails      :
Exception             : DnsClient.DnsResponseException: Query 27847 => [REDACTED].mongodb.net IN TXT on
                        10.0.8.228:53 failed with an error. ---> System.IO.FileNotFoundException: Could not load file
                        or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral,
                        PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file
                        specified.
                           at DnsClient.Internal.PooledBytes..ctor(Int32 length)
                           at DnsClient.DnsDatagramWriter..ctor()
                           at DnsClient.DnsUdpMessageHandler.Query(IPEndPoint server, DnsRequestMessage request,
                        TimeSpan timeout)
                           at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings,
                        DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
                           --- End of inner exception stack trace ---
                           at DnsClient.LookupClient.ResolveQuery(IReadOnlyList`1 servers, DnsQuerySettings settings,
                        DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit)
                           at DnsClient.LookupClient.QueryInternal(DnsQuestion question, DnsQuerySettings
                        queryOptions, IReadOnlyCollection`1 servers)
                           at MongoDB.Driver.Core.Misc.DnsClientWrapper.ResolveTxtRecords(String domainName,
                        CancellationToken cancellationToken)
                           at MongoDB.Driver.Core.Configuration.ConnectionString.Resolve(Boolean resolveHosts,
                        CancellationToken cancellationToken)
                           at MongoDB.Driver.MongoUrl.Resolve(Boolean resolveHosts, CancellationToken
                        cancellationToken)
                           at MongoDB.Driver.MongoClientSettings.FromUrl(MongoUrl url)
                           at Mdbc.Commands.ConnectCommand.BeginProcessing()
                           at System.Management.Automation.Cmdlet.DoBeginProcessing()
                           at System.Management.Automation.CommandProcessorBase.DoBegin()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Connect-Mdbc], DnsResponseException
FullyQualifiedErrorId : DnsClient.DnsResponseException,Mdbc.Commands.ConnectCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, K:\DattoSpy\Powershell\MongoDb-Atlas\Connect-MongoDbAtlas.ps1: line 5
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

Past issues that appear to show similar error responses appeared to be resolved by a module version update but I'm on the latest:

```powershell
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                                      
---------- -------    ----                                ----------------                                                                                                                                      
Binary     6.5.11     Mdbc                                {Add-MdbcCollection, Add-MdbcData, Connect-Mdbc, Export-MdbcData...}                                                                                  
```

Here is the source for the script I'm running with redacted username, password, and part of hostname:

```powershell
Import-Module Mdbc

$uri = "mongodb+srv://[username]:[password]@[hostname].mongodb.net/bdrSpy?retryWrites=true&w=majority"
Try {
    Connect-Mdbc -ConnectionString $uri -DatabaseName "bdrSpy" -CollectionName "tests"
} Catch {
    $_ | Select *
}

Get-MdbcData -As PS | Format-Table
```

I'm able to connect to this database without issue using MongoDB Compass in Windows.

- I've changed my DNS server to use Google and Cloudflare separately with no success. My LAN DNS ultimately forwards to Cloudflare by default.
- This script worked yesterday when I wrote it and for a time after that
- It has returned this response every time I've tried to connect with Powershell on Windows 11 Enterprise today
- Still occurs after a host reboot
- Response is the same in Admin Powershell
- Ran `Add-WindowsCapability -Name NetFX3 -Online` but did not change outcome.

I'm not super new to Powershell and Windows but I certainly have a greater comfort with nix-based environments. Not sure which part of the error response I could key in on to find the fix.

**Comment by wci-lrjackson** [comment]
I ran into this same issue and poked at it until I found something that worked (though I'm not sure if it's a best practice). On Atlas, if you change your connection driver to `C# / .NET` and select `2.4 or later`, it gives you a `mongodb://` protocol connection string with all the shards. This seems to get around the issues caused by the newer `mongodb+srv://` protocol.

**Comment by nightroman** [comment]
@wci-lrjackson Thank you. The latest Mdbc uses C# driver 2.19.0, i.e. definitely "2.4 or later". I am not sure if it's a best practice either, but I think this tip makes sense.
